### ISSUE TITLE
inference script throwing an error

### ISSUE THREAD

**Issue by saahiluppal** [singhaxn/COVID-19_CXR_AI#2]
1. I've installed all the requirements
2. I've downloaded the model from the given script

Running ```inference.py``` gives the following error
```bash
$ python3 inference.py --xraypath [/path/to/xray] --config model-config.json

<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
Traceback (most recent call last):
  File "inference.py", line 295, in <module>
    p, c, q = infer(args.config, args.xraypath, args.heatmappath)
  File "inference.py", line 255, in infer
    regions_df = segment(config, [img_file], False)
  File "inference.py", line 121, in segment
    inputs, preds, _, masks = segmenter.get_preds(dl=dl, with_input=True, with_decoded=True)
  File "/usr/local/lib/python3.7/dist-packages/fastai/learner.py", line 235, in get_preds
    self._do_epoch_validate(dl=dl)
  File "/usr/local/lib/python3.7/dist-packages/fastai/learner.py", line 188, in _do_epoch_validate
    with torch.no_grad(): self._with_events(self.all_batches, 'validate', CancelValidException)
  File "/usr/local/lib/python3.7/dist-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/usr/local/lib/python3.7/dist-packages/fastai/learner.py", line 161, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/usr/local/lib/python3.7/dist-packages/fastai/data/load.py", line 102, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 874, in __init__
    super(_MultiProcessingDataLoaderIter, self).__init__(loader)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 495, in __init__
    self._persistent_workers = loader.persistent_workers
AttributeError: '_FakeLoader' object has no attribute 'persistent_workers'
```

Results can be reproduced in colab

**Comment by singhaxn** [comment]
Can you tell me what version of torch you have? ( Please see [setup-user.sh](https://github.com/singhaxn/COVID-19_CXR_AI/blob/master/env/setup-user.sh) ).

I have encountered this issue myself when trying to load the model in torch > 1.6.0

**Comment by saahiluppal** [comment]
Thanks for the prompt reply. Now i've installed pytorch using the following command as suggested by you
```bash
$ pip3 install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
```
Now running the same inference command gives following error
```bash
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
Traceback (most recent call last):
  File "inference.py", line 295, in <module>
    p, c, q = infer(args.config, args.xraypath, args.heatmappath)
  File "inference.py", line 259, in infer
    config, [img_file], regions_df, heatmap_path, False
  File "inference.py", line 160, in classify
    classifier = load_learner(config["classifier"])
  File "/usr/local/lib/python3.7/dist-packages/fastai/learner.py", line 547, in load_learner
    res = torch.load(fname, map_location='cpu' if cpu else None)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'get_cropped_image' on <module '__main__'>
```
Refer to this [notebook](https://gist.github.com/saahiluppal/deca567a10257aee667a53c467c5bec0)

**Comment by singhaxn** [comment]
It works if I add the following code block to your notebook (the image is one of my own, of course):

```
from inference import infer

get_cropped_image = None

p, c, q = infer("/content/COVID-19_CXR_AI/inference/model-config.json", "/content/COVID-19_CXR_AI/COVID-19 (1).png")
p, c, q
```

My best guess is, for some reason, the `get_cropped_image` declared in inference.py is not in the global scope under colab. If you can move forward with this, please do. Otherwise, I'll investigate further and update this thread when I have a solution.

Suggestions are welcome.

**Comment by saahiluppal** [comment]
First of all thank you for this awesome project.
And thank you for your help. I really appreciate it.

I now understand this project and looking forward to contribute to this.
